server.port: 8080

spring:
  output.ansi.enabled: "ALWAYS"
  application.name: "clients"

  redis:
    host: "localhost"
    port: 6379

  datasource:
    # Friendly reminder: Never share sensitive information in config files!
    url: "jdbc:postgresql://localhost:5432/clients"
    username: "postgres"
    password: "Secret123"
    driver-class-name: "org.postgresql.Driver"

  jpa.properties:
    hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"